import Head from "next/head";
import styles from "../styles/Home.module.scss";
import NavLayout from "../components/Layouts/NavLayout";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles["home"]}>
      <Head>
        <title>IChatMo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["home__bg-container"]}></div>
      <main className={styles["home__main"]}>
        <h1 className={styles["home__title"]}>
          Welcome to IChat
          <span className={styles["home__title--blue"]}>Mo</span>!
        </h1>
        <p className={styles["home__subtitle"]}>
          An easy-to-use chat anyone application
        </p>
        <Link href={"/signup"}>
          <a className={styles["home__cta"]}>Get Started →</a>
        </Link>
      </main>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
